# Permalinks
permalink:           none

# Setup
title:               Chijioke Okafo
tagline:             web.developer/professional.bmx.rider/bicycle.witchdoctor
url:                 http://chijiokeokafo.github.io
paginate:            4
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Chijioke Okafo
  url:               https://instagram.com/chijiokeokafo
  email:             chijiokeokafo@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/chijiokeokafo/chijiokeokafo

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
